### ISSUE TITLE
stop_all() callback

### ISSUE THREAD

**Issue by vdeville** [sbrl/soundbox#4]
Can you add the possibility to call the callback of all song played when call stop_all() ?

For example if song XXX.mp3 and YYYY.mp3 is play, and i call soundbox.stop_all(), can you terminate each song that is currently playing and call the callback of play() method ?

Or add killed callback for each song ?

Thanks ;)

**Comment by vdeville** [comment]
This work ;)
```javascript
stop_all() {
    // Pause all currently playing sounds
    for (let instance of this.instances) {
        instance.dispatchEvent((new Event('ended')));
         instance.pause();
    }
    this.instances = []; // Empty the instances array
}
```

**Comment by sbrl** [comment]
Ah, good spot! Please see my comment on #5, and then I'll get to merging.
