### ISSUE TITLE
demo does not work

### ISSUE THREAD

**Issue by metalim** [sbrl/soundbox#7]
https://sbrl.github.io/soundbox/example.html
.jsm file is not loaded properly, and throws error in Chrome:
`soundbox.jsm:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.`

Firefox reports:
`Loading failed for the module with source “https://sbrl.github.io/soundbox/soundbox.jsm”.`

**Comment by sbrl** [comment]
Thanks for the report! I've learnt quite a bit about ES6 file extensions recently - I must have forgotten to come back around and update this. Thanks for the reminder! I'll do it now.

**Comment by sbrl** [comment]
Fixed! I've just released [v0.3.5](https://github.com/sbrl/soundbox/releases/tag/v0.3.5). Does that work now for you, @metalim?
